### ISSUE TITLE
no mob spawns

### ISSUE THREAD

**Issue by okzerus** [MCTeamPotato/DoesPotatoTick#2]
after running around the world for a while and spawning mobs, moving to other chunks or loading new ones gives absolutely no mobs.
only mobs that are being spawned through structures (like villagers) or blocks (like bees) loaded.

I assume this is because old mobs are not ticking, so it means that they can't despawn as well.
in some areas that were loaded before mobs keep spawning even after deleting them.
using latest version of DPT (3.2) and forge

**Comment by Kasualix** [comment]
Failed to reproduce in [my pack](https://www.curseforge.com/minecraft/modpacks/tankoptimization).
Do you have other mods installed? Can you provide a list?

**Comment by Kasualix** [comment]
😨

**Comment by okzerus** [comment]
> 😨

I'm sorry xD

**Comment by okzerus** [comment]
deleted adaptive performance and still testing, everything looking good so far. I'll keep testing, but if in 10 minutes this bug won't appear again, I'm gonna go say to the dev that his module "disabling" only disables my nerves, one after another.

**Comment by okzerus** [comment]
well, yeah. I guess that adaptive performance and DPT don't want to cooperate with each other.
but actually, deleting adaptive performance is a big problem for my modpack. maybe you didn't know, but currently almost every mod that adds custom trees has one "tiny" issue - decaying leaves. everyone making trees so big, that leaves start decaying, cause they're spawn too far away from the main log.

I half-fixed this issue by limiting the item drops of the same type in adaptive performance, but now, without this mod, almost every biome in my modpack is flooded with saplings, making my server lag..

do you know any mods that limits dropped items of the same type or prevents leaves from decaying by any chance?

**Comment by Kasualix** [comment]
You can also try enabling "slow down items in the world" in dpt config to slow down saplings item entities.

**Comment by Kasualix** [comment]
close this.
I will add incompatible info on CurseForge.

**Comment by okzerus** [comment]
already tried with Fast Leaf Decay, it doesn't override the vanilla decaying mechanic, making it the same as without the mod.
I'm not sure if slow-down items will do anything, because mainly this lag from a big amount of items, both tps and fps (from 60 to 30 in dense forest biomes) cause of Loot Beams mod.

**Comment by Kasualix** [comment]
Maybe you can use KubeJS to write a items cleanup script to remove items in the world on schedule.

**Comment by Kasualix** [comment]
or simply, /kill @e[type=item], or with Cuneiform /killitems
