### ISSUE TITLE
Does it affect vanilla?

### ISSUE THREAD

**Issue by NerdTo** [MCTeamPotato/DoesPotatoTick#3]
Also, what about 1.19.4?

**Comment by Kasualix** [comment]
If FTB Chunks has 1194, then I can port DPT to 1194.
DPT without FTB Chunks is uncontrollable and dangerous.

**Comment by NerdTo** [comment]
ok

**Comment by Kasualix** [comment]
I don't understand what the question in your title means. I'm Chinese, my English may not be very good, could you tell me more about it?

**Comment by NerdTo** [comment]
Что такое FTB Chunks?

**Comment by NerdTo** [comment]
Ломает ли ДПТ какие-то фермы?

**Comment by NerdTo** [comment]
In fact, I don't understand English either :) I'm Russian.

**Comment by Kasualix** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge

**Comment by NerdTo** [comment]
> https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge

Is there a Fabric?

**Comment by Kasualix** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric

**Comment by NerdTo** [comment]
Thanks, but it's a pity it's not out yet on 1.19.4

**Comment by Kasualix** [comment]
and as the desc tells
![IMG_20230501_015110](https://user-images.githubusercontent.com/110756250/235368460-00f37155-c744-4990-950b-1d7029d1cf37.jpg)

**Comment by NerdTo** [comment]
And what about vanilla(Does it break any farm, mechanics, etc.)

**Comment by Kasualix** [comment]
it breaks farm when players are far to the place if you don't write down entity blacklist in config or use ftb chunks to claim the farm chunks

**Comment by NerdTo** [comment]
hm

**Comment by Kasualix** [comment]
now you mean why i said "uncontrollable and dangerous"?

**Comment by NerdTo** [comment]
yes
