### ISSUE TITLE
[SERVER CRASH] Server crash on startup when FTBChunks not installed

### ISSUE THREAD

**Issue by Tempest-5ky** [MCTeamPotato/DoesPotatoTick#4]
More or less what it says on the tin! 
Error: https://mclo.gs/lLo4bA1
Crashlog: https://mclo.gs/F5ObXzI

**Comment by Kasualix** [comment]
If you download dpt from modrinth, then you should know that FTB Chunks is not available on modrinth currently so I can't add it to the dependence list.

**Comment by Tempest-5ky** [comment]
Ah! It was not clear that it was a hard dependency, only that an integration was present. Apologies.

**Comment by Kasualix** [comment]
FTB Chunks is no longer a requirement in [3.5.0](https://modrinth.com/mod/does-potato-tick/version/hB1zRFYn)
