### ISSUE TITLE
[1.18.2] DoesPotatoTick is Broken

### ISSUE THREAD

**Issue by DeshiDesu** [MCTeamPotato/DoesPotatoTick#5]
Installed mods:
>does_potato_tick-1.18.2-3.6.0.jar
Forge 40.2.9

[latest.log](https://github.com/MCTeamPotato/DoesPotatoTick/files/11783601/latest.log)
[latest.log](https://github.com/MCTeamPotato/DoesPotatoTick/files/11783625/latest.log)

![2023-06-18_22 40 15](https://github.com/MCTeamPotato/DoesPotatoTick/assets/120287925/03718426-5b74-4377-8905-116c9e476ab6)
![2023-06-18_22 48 54](https://github.com/MCTeamPotato/DoesPotatoTick/assets/120287925/cfd6f4c4-fd20-408a-ae24-df66b6e43203)

Can't move or world wont load when installed in a large modpack. I have no other mods installed other than DoesPotatoTick.

**Comment by DeshiDesu** [comment]
Turns out observable was a dependency...

**Comment by Kasualix** [comment]
Oh sorry
done.
